apiVersion: v1
kind: ConfigMap
metadata:
  name: hackmanite-config
  namespace: hackmanite
data:
  NLP_SERVICE_URL: "http://nlp:8000"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_CLIENT_ID: "hackmanite-pipeline"
  SHARED_CACHE_DIR: "/app/uploads/pipeline-cache"
  UPLOAD_DIR: "/app/uploads"
  NEXT_PUBLIC_APP_URL: "http://hackmanite.local"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
