apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackmanite-ingress
  namespace: hackmanite
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: hackmanite.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
