apiVersion: v1
kind: Secret
metadata:
  name: hackmanite-secret
  namespace: hackmanite
type: Opaque
data:
  # postgresql://postgres:postgres@postgres:5432/hackmanite?schema=public&connection_limit=10
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvaGFja21hbml0ZT9zY2hlbWE9cHVibGljJmNvbm5lY3Rpb25fbGltaXQ9MTA=
  # d8a4362b9f3fe2b0d0c3eb1a47df2c6c0e81b6e4d07b4694b29c91b5c468e21a
  SESSION_SECRET: ZDhhNDM2MmI5ZjNmZTJiMGQwYzNlYjFhNDdkZjJjNmMwZTgxYjZlNGQwN2I0Njk0YjI5YzkxYjVjNDY4ZTIxYQ==
  # 2SpqHqFvK00ckGpNkHdKOJRuuCkCUGHi
  MISTRAL_API_KEY: MlNwcUhxRnZLMDBja0dwTmtIZEtPSlJ1dUNrQ1VHSGk=
